# app.yaml

runtime: python310
service: default
entrypoint: gunicorn -b :$PORT app.main:app

instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1

env_variables:
  FETCH_INTERVAL_SECONDS: "60"
  BOT_LOOP_INTERVAL_SECONDS: "15"
  MAX_ALERT_AGE_SECONDS: "70"
  
  BYBIT_API_KEY: "sz3y2CfXOuAVIcQpsI"
  BYBIT_API_SECRET: "jyuJkCm0aDfdNWG5XL9xmoRV5O5TOjbZ0hfl"