runtime: python311
service: default
instance_class: F1
entrypoint: gunicorn -b :$PORT main:app # Jawny entrypoint dla Gunicorna

automatic_scaling:
  min_instances: 1
  max_instances: 1

readiness_check:
  path: "/"
liveness_check:
  path: "/"