# Lokalizacja: /cloudbuild-bot.yaml

steps:
# Krok 1: Zbuduj obraz Docker
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Image'
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/$PROJECT_ID/trading-bot-image/trading-bot-service:$SHORT_SHA', '--file', 'bot_service/Dockerfile', '.']

# Krok 2: Wypchnij obraz do Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Image'
  args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/trading-bot-image/trading-bot-service:$SHORT_SHA']

# Krok 3: Wdróż obraz na Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'trading-bot-service'
    - '--image'
    - 'europe-central2-docker.pkg.dev/$PROJECT_ID/trading-bot-image/trading-bot-service:$SHORT_SHA'
    - '--region'
    - 'europe-central2'
    - '--platform'
    - 'managed'
    - '--service-account'
    - 'trading-bot-463318@appspot.gserviceaccount.com'
    - '--vpc-connector'
    - 'app-connector-warsaw'
    - '--vpc-egress'
    - 'all'
images:
- 'europe-central2-docker.pkg.dev/$PROJECT_ID/trading-bot-image/trading-bot-service:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY