#Lokalizacja: cloudbuild-collector.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'europe-central2-docker.pkg.dev/${PROJECT_ID}/trading-bot-image/data-collector-service:latest',
    
    '--file', 'collector_service/Dockerfile',

    '.'
  ]
images:
- 'europe-central2-docker.pkg.dev/${PROJECT_ID}/trading-bot-image/data-collector-service:latest'