# Lokalizacja: /cloudbuild-bot.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/trading-bot-image/trading-bot-service:$SHORT_SHA', '--file', 'bot_service/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/trading-bot-image/trading-bot-service:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'trading-bot-service'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/trading-bot-image/trading-bot-service:$SHORT_SHA'
    # --- KLUCZOWA ZMIANA: Zmiana regionu na zgodny z Firestore ---
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--service-account'
    - 'trading-bot-runner@$PROJECT_ID.iam.gserviceaccount.com'
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/trading-bot-image/trading-bot-service:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY