# Lokalizacja: /cloudbuild-collector.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/$PROJECT_ID/trading-bot-image/data-collector-service:$SHORT_SHA', '--file', 'collector_service/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/trading-bot-image/data-collector-service:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'data-collector-service'
    - '--image'
    - 'europe-central2-docker.pkg.dev/$PROJECT_ID/trading-bot-image/data-collector-service:$SHORT_SHA'
    - '--region'
    - 'europe-central2'
    - '--platform'
    - 'managed'
    # --- OSTATECZNA ZMIANA: Usługa działa z tą samą tożsamością co Cloud Build ---
    - '--service-account'
    - 'trading-bot-463318@appspot.gserviceaccount.com'
images:
- 'europe-central2-docker.pkg.dev/$PROJECT_ID/trading-bot-image/data-collector-service:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY