# Krok 1: Użyj tego samego lekkiego obrazu Pythona
FROM python:3.11-slim

# Krok 2: Ustaw zmienne środowiskowe
ENV PYTHONUNBUFFERED 1

# Krok 3: Ustaw folder roboczy
WORKDIR /app

# Krok 4: Skopiuj plik z zależnościami i zainstaluj je
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Krok 5: Skopiuj cały kod aplikacji
COPY . .

# Krok 6: Zdefiniuj komendę, która uruchomi APLIKACJĘ BOTA używając fabryki.
# ### POPRAWKA: Zmieniono main:app na "main:create_app()" ###
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 "main:create_app()"