# orderflow_engine/config_symbols.py
from typing import List, Dict, Any

# Lista 49 symboli (bez .P)
SYMBOLS_TO_WATCH_CLEAN = [
    "DOGEUSDT", "TRXUSDT", "ADAUSDT", "XLMUSDT", "HBARUSDT", "ONDOUSDT", "ARBUSDT",
    "ALGOUSDT", "POLUSDT", "KASUSDT", "XRPUSDT", "UNIUSDT", "TIAUSDT", "TAOUSDT",
    "SUIUSDT", "SOLUSDT", "NEARUSDT", "LTCUSDT", "LINKUSDT", "ICPUSDT", "DOTUSDT",
    "APTUSDT", "ATOMUSDT", "ETHUSDT", "BNBUSDT", "AVAXUSDT", "BCHUSDT",
    "AAVEUSDT", "WLDUSDT", "ENAUSDT", "SEIUSDT", "IMXUSDT", "RENDERUSDT", "ETCUSDT", # POPRAWIONE: ETCUSDT
    "FLRUSDT", "TONUSDT", "OPUSDT", "INJUSDT", "HYPEUSDT", "PYTHUSDT", "STXUSDT",
    "ORDIUSDT", "AXSUSDT", "SANDUSDT", "XMRUSDT", "MNTUSDT", "CROUSDT", "ZECUSDT"
]
BENCHMARK_SYMBOL = "BTCUSDT"
ALL_SYMBOLS_FOR_WS = SYMBOLS_TO_WATCH_CLEAN + [BENCHMARK_SYMBOL]