# orderflow_engine/config_symbols.py
from typing import List, Dict, Any

# 65 par + BENCHMARK_SYMBOL (BTCUSDT) = 66 unikalnych (bez .P).
# Źródło: Firestore symbols_to_watch; duplikaty (TIA/OP/SEI/XTZ) odrzucone, kolejność zachowana.
SYMBOLS_TO_WATCH_CLEAN = [
    "DOGEUSDT", "TRXUSDT", "ADAUSDT", "XLMUSDT", "HBARUSDT", "ONDOUSDT", "ARBUSDT",
    "ALGOUSDT", "POLUSDT", "KASUSDT", "XRPUSDT", "UNIUSDT", "TIAUSDT", "TAOUSDT",
    "SUIUSDT", "SOLUSDT", "NEARUSDT", "LTCUSDT", "LINKUSDT", "ICPUSDT", "DOTUSDT",
    "APTUSDT", "ATOMUSDT", "ETHUSDT", "BNBUSDT", "AVAXUSDT", "BCHUSDT",
    "AAVEUSDT", "WLDUSDT", "ENAUSDT", "SEIUSDT", "IMXUSDT", "RENDERUSDT", "ETCUSDT",
    "FLRUSDT", "TONUSDT", "OPUSDT", "INJUSDT", "HYPEUSDT", "PYTHUSDT", "STXUSDT",
    "ORDIUSDT", "AXSUSDT", "SANDUSDT", "XMRUSDT", "MNTUSDT", "CROUSDT", "ZECUSDT",
    "CRVUSDT", "PENDLEUSDT", "VIRTUALUSDT", "WIFUSDT", "LDOUSDT", "JTOUSDT", "ZROUSDT",
    "XTZUSDT", "RUNEUSDT", "EIGENUSDT", "THETAUSDT", "GRTUSDT", "STRKUSDT", "JASMYUSDT",
    "GRASSUSDT", "COMPUSDT", "ENSUSDT",
]
BENCHMARK_SYMBOL = "BTCUSDT"
ALL_SYMBOLS_FOR_WS = SYMBOLS_TO_WATCH_CLEAN + [BENCHMARK_SYMBOL]
