name: Deploy Data Collector to Cloud Run

on:
  push:
    branches:
      - div
    paths:
      - '.github/workflows/deploy-collector.yml'
      - 'cloudbuild-collector.yaml'
      - 'collector_service/**'
      - 'shared_lib/**'
      - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-actions-sa@trading-bot-463318.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Build and push image via Cloud Build
        run: |-
          gcloud builds submit . --config=cloudbuild-collector.yaml \
            --impersonate-service-account=service-785819958951@gcp-sa-cloudbuild.iam.gserviceaccount.com

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy data-collector-service \
            --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trading-bot-image/data-collector-service:latest \
            --region europe-central2 \
            --platform managed \
            --allow-unauthenticated \
            --service-account trading-bot-463318@appspot.gserviceaccount.com