name: Deploy Data Collector to Cloud Run

on:
  push:
    branches:
      - div # Lub Twoja główna gałąź
    paths:
      - 'trading_bot/data_collector.py'
      - 'trading_bot/collector_main.py'  # <-- NOWY PLIK
      - 'Dockerfile.collector'           # <-- NOWY PLIK
      - 'trading_bot/firebase_client.py'
      - 'trading_bot/constants.py'

jobs:
  deploy-collector:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/785819958951/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@trading-bot-463318.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      # --- POCZĄTEK ZMIAN: Budowanie i wdrażanie kontenera ---
      
      - name: Configure Docker
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Build and Push Docker image for Collector
        run: |-
          gcloud builds submit --tag europe-central2-docker.pkg.dev/trading-bot-463318/trading-bot-image/data-collector-service:latest --file=Dockerfile.collector

      - name: Deploy Collector to Cloud Run
        run: |-
          gcloud run deploy data-collector-service \
            --image europe-central2-docker.pkg.dev/trading-bot-463318/trading-bot-image/data-collector-service:latest \
            --region europe-central2 \
            --allow-unauthenticated \
            --vpc-connector app-connector-warsaw \
            --vpc-egress all
            
      # --- KONIEC ZMIAN ---